application: playlist-spike
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /styles
  static_dir: static/styles
- url: /images
  static_dir: static/images
- url: /scripts
  static_dir: static/scripts
- url: /.*
  script: web.app
